library/library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('accounts.urls', 'accounts')),
    path('', include('webapp.urls', 'webapp')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

library/webapp/urls.py
from django.urls import path
from webapp.views import BookListView, UserView, BookDetailView, BookDeleteView, BookCreateView, AuthorCreateView, AuthorDetailView, AuthorListView, BookUpdateView, AuthorDeleteView, AuthorUpdateView

app_name = 'webapp'

urlpatterns = [
    path('', BookListView.as_view(), name='book_list'),
    path('book/<int:pk>', BookDetailView.as_view(), name='book_detail'),
    path('book/<int:pk>', BookUpdateView.as_view(), name='book_update'),
    path('book/create/', BookCreateView.as_view(), name='book_create'),
    path('book/<int:pk>', BookDeleteView.as_view(), name='book_delete'),
    path('authors/<int:pk>', AuthorUpdateView.as_view(), name='author_update'),
    path('authors/<int:pk>', AuthorDeleteView.as_view(), name='author_delete'),
    path('users/<int:pk>', UserView.as_view(), name='user_info'),
    path('authors/<int:pk>', AuthorDetailView.as_view(), name='author_detail'),
    path('authors/create/', AuthorCreateView.as_view(), name='author_create'),
    path('authors/', AuthorListView.as_view(), name='author_list')
]

library/webapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class SoftDeleteManager(models.Manager):
    def active(self):
        return self.filter(is_deleted=False)

    def deleted(self):
        return self.filter(is_deleted=True)

class Author(models.Model):
    name = models.CharField(max_length=55, verbose_name="Имя")
    surname = models.CharField(max_length=55, verbose_name="Фамилия")
    birthdate = models.DateField(null=True, blank=True, verbose_name="Дата рождения")
    dateofdeath = models.DateField(null=True, blank=True, verbose_name="Дата смерти")
    biography = models.TextField(null=True, blank=True, verbose_name="Биография")
    photo = models.ImageField(null=True, blank=True, verbose_name="Фотография")
    is_deleted = models.BooleanField(default=False)

    objects = SoftDeleteManager()

    def __str__(self):
        return self.surname

class Book(models.Model):
    title = models.CharField(max_length=55, verbose_name='Название')
    author = models.ForeignKey(Author, on_delete=models.PROTECT)
    publicationdate = models.DateField()
    file = models.FileField(null=True, blank=True)
    cover = models.ImageField(null=True, blank=True, verbose_name="Обложка")
    description = models.TextField(max_length=2500, null=True, blank=True, verbose_name="Описание")

    def __str__(self):
        return self.title

class Bookmark(models.Model):
    bookmark_id = models.AutoField(primary_key=True)
    user = models.OneToOneField(User, on_delete=models.PROTECT, related_name='bookmarks')
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='bookmarks')

class UserInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.PROTECT, verbose_name="Пользователь")
    avatar = models.FileField(null=True, blank=True, verbose_name="Аватар")
    phone_number = models.CharField(max_length=15, verbose_name="Номер телефона")
    bookmarks = models.ManyToManyField(Bookmark, blank=True, related_name='bookmarks', verbose_name='Закладки')

library/webapp/forms.py
import datetime
from django import forms
from webapp.models import Book, Author


class AuthorCreateForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['name', 'surname', 'birthdate', 'dateofdeath', 'photo', 'biography']
        widgets = {
            'birthdate': forms.SelectDateWidget(empty_label=('Год', 'Месяц', 'День'),
                                               years=[r for r in range(1970, datetime.date.today().year + 1)],
                                               attrs={
                                                   'class': 'form-control form-control-sm '
                                                            'shadow-none w-25 d-inline-block'}),
            'dateofdeath': forms.SelectDateWidget(empty_label=('Год', 'Месяц', 'День'),
                                               years=[r for r in range(1970, datetime.date.today().year + 1)],
                                               attrs={
                                                   'class': 'form-control form-control-sm '
                                                            'shadow-none w-25 d-inline-block',
                                                   'placeholder': 'Дата рождения', }),
            'name': forms.TextInput(
                attrs={'class': 'form-control form-control-sm shadow-none',
                       'placeholder': 'Имя'}),
            'surname': forms.TextInput(
                attrs={'class': 'form-control form-control-sm shadow-none',
                       'placeholder': 'Фамилия'}),
            'biography': forms.Textarea(attrs={'class': 'form-control form-control-sm shadow-none',
                                               'placeholder': 'Биография  ', 'rows': '4'}),
        }


class BookForm(forms.ModelForm):
    author = forms.ModelChoiceField(queryset=Author.objects.filter(is_deleted=False),
                                    empty_label='Неизвестен',
                                    widget=forms.Select
                                    (attrs={'class': 'form-control form-control-sm shadow-none', }),
                                    label='Автор', required=False)

    class Meta:
        model = Book
        fields = ['title', 'author', 'cover', 'file', 'publicationdate', 'description']
        widgets = {
            'name': forms.TextInput(
                attrs={'class': 'form-control form-control-sm shadow-none',
                       'placeholder': 'Название книги'}),
            'created_date': forms.TextInput(
                attrs={'class': 'form-control form-control-sm shadow-none',
                       'placeholder': 'Дата публикации'}),
            'description': forms.TextInput(
                attrs={'class': 'form-control form-control-sm shadow-none',
                       'placeholder': 'Описание'}),
        }

library/webapp/views.py
from django.views.generic import DetailView, CreateView, UpdateView, View, DeleteView, ListView, TemplateView
from django.urls import reverse, reverse_lazy
from webapp.models import UserInfo, Book, Bookmark, Author
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import redirect, render, get_object_or_404
from webapp.forms import BookForm, AuthorCreateForm

class BookListView(ListView):
    model = Book
    template_name = 'book_list.html'

    def get_queryset(self):
        return super().get_queryset().order_by('title')

class BookDetailView(DeleteView):
    model = Book
    template_name = 'book_detail.html'

class BookCreateView(PermissionRequiredMixin, LoginRequiredMixin, CreateView):
    model = Book
    template_name = 'book_create.html'
    form_class = BookForm
    permission_required = 'superuser'


class BookUpdateView(PermissionRequiredMixin, LoginRequiredMixin, UpdateView):
    model = Book
    template_name = 'book_update.html'
    form_class = BookForm
    permission_required = 'superuser'

    def get_success_url(self):
        return reverse('webapp:book_list')

class BookDeleteView(PermissionRequiredMixin, LoginRequiredMixin, DeleteView):
    model = Book
    permission_required = 'superuser'

def soft_delete_author(request, pk):
    author = get_object_or_404(Author, pk=pk)
    author.is_deleted = True
    author.save()
    return reverse('webapp:author_list')


class UserView(TemplateView, LoginRequiredMixin):
    template_name = "user_info.html"

    def dispatch(self, request, *args, **kwargs):
        if not UserInfo.objects.filter(user=request.user).exists():
            return redirect(reverse("edit_profile"))
        context = {
            'selected_user': request.user
        }
        return render(request, self.template_name, context)

class UserListView(ListView):
    model = UserInfo
    template_name = 'user_list.hmtl'

class AuthorListView(ListView):
    model = Author
    template_name = 'author_list.html'
    permission_required = 'superuser'

    def get_queryset(self):
        return Author.objects.filter(is_deleted=False)

class AuthorDetailView(DetailView):
    model = Author
    template_name = 'author_detail.html'


class AuthorDeleteView(PermissionRequiredMixin, LoginRequiredMixin, DeleteView):
    model = Author
    template_name = 'author_delete'
    permission_required = 'superuser'

class AuthorUpdateView(PermissionRequiredMixin, LoginRequiredMixin, UpdateView):
    model = Author
    template_name = 'author_update.html'
    form_class = AuthorCreateForm
    permission_required = 'superuser'

    def get_success_url(self):
        return reverse('webapp:author_list')


class AuthorCreateView(PermissionRequiredMixin, LoginRequiredMixin, CreateView):
    model = Author
    template_name = 'author_create.html'
    form_class = AuthorCreateForm
    permission_required = 'superuser'

library/webapp/templates/author_create.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h2 class="text-center">Добавление автора</h2>
        <form action="{% url 'webapp:author_create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
                {{ field.errors }}
                <div class="row">
                    <div class="col-sm-2 mt-3">
                        {{ field.label_tag }}
                    </div>
                    <div class="col-sm-10 mt-3">
                        {{ field }}
                    </div>
                </div>
            {% endfor %}
             <div class="mt-3">
                <button type="submit" class="btn btn-success d-block m-auto w-25" style="width: 125px">Добавить</button>
            </div>
        </form>
    </div>
{% endblock %}

library/webapp/templates/author_detail.html
{% extends 'base.html' %}
{% block title %}{{ author.name }} {{ author.surname }}{% endblock %}
{% block content %}
    <h1 class="mt-2">{{ author.name }} {{ author.surname }}</h1>
    <p>{{ article.birthdate }} | {{ article.dateofdeath }}
    </p>
    <div class="img-wrapper">
        <img class="w-50" src="{{ author.photo }}" alt="">
    </div>
    <p class="mt-3 pre-spaces">{{ article.biography }}</p>
    {% if user.is_superuser %}
        <a class="float-right" href="{% url 'webapp:author_update' article.pk %}">Редактировать</a>
        <a class="float-right" href="{% url 'webapp:author_delete' article.pk %}">Удалить</a>
    {% endif %}
{% endblock %}

library/webapp/templates/author_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Авторы{% endblock %}
{% block content %}
    <div class="list-group">
        {% for author in author_list %}
            <div class="jumbotron">
                <h1 class="display-4">{{ author.name }} {{ author.surname }}</h1>
                <p>Дата рождения: {{ author.birthdate }}</p>
                <p>Дата смерти: {{ author.dateofdeath }}</p>
                <hr class="my-4">
                <a class="btn btn-primary btn-lg" href="{% url 'webapp:author_detail' author.pk %}" role="button">
                    {{ author.name }} {{ author.surname }}</a>
            </div>
        {% endfor %}
    </div>
{% endblock %}

library/webapp/templates/author_update.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    <div class="container">
        <form action="{% url 'webapp:author_update' author.pk %}" method="post" class="mt-4">
            {% csrf_token %}
                <div class="form-group row" style="margin-top: 150px">
                    <label for="id_name" class="col-sm-2 col-form-label col-form-label-sm">ФИО</label>
                    <div class="col-sm-6">
                        {{ form.name }}

                        {{ form.surname }}
                        <small class="form-text text-muted">Обязательное поле</small>
                        {% for i in form.name.errors %}
                            <p class="font-weight-light text-danger d-block small text-center pb-0 mb-0">{{ i }}</p>
                        {% endfor %}
                    </div>
                </div>
                <div class="form-group row">
                    <label for="id_first_name" class="col-sm-2 col-form-label col-form-label-sm">Дата рождения</label>
                    <div class="col-sm-6">
                        {{ form.birthdate }}
                        {% for i in form.birthdate.errors %}
                            <p class="font-weight-light text-danger d-block small text-center pb-0 mb-0">{{ i }}</p>
                        {% endfor %}
                    </div>
                </div>
                <div class="form-group row">
                    <label for="id_first_name" class="col-sm-2 col-form-label col-form-label-sm">Дата смерти</label>
                    <div class="col-sm-6">
                        {{ form.dateofdeath }}
                        {% for i in form.dateofdeath.errors %}
                            <p class="font-weight-light text-danger d-block small text-center pb-0 mb-0">{{ i }}</p>
                        {% endfor %}
                    </div>
                </div>
                <div class="form-group row">
                    <label for="id_biography" class="col-sm-2 col-form-label col-form-label-sm">Биограция</label>
                    <div class="col-sm-6">
                        {{ form.biography }}
                        {% for i in form.biography.errors %}
                            <p class="font-weight-light text-danger d-block small text-center pb-0 mb-0">{{ i }}</p>
                        {% endfor %}
                    </div>
                </div>
                <div class="form-group row">
                    <label for="id_photography" class="col-sm-2 col-form-label col-form-label-sm">Фото</label>
                    <div class="col-sm-6">
                        {{ form.photo }}
                        {% for i in form.photo.errors %}
                            <p class="font-weight-light text-danger d-block small text-center pb-0 mb-0">{{ i }}</p>
                        {% endfor %}
                    </div>
                </div>
            <button class="btn btn-sm btn-outline-info">Submit</button>
        </form>
    </div>
{% endblock %}

library/webapp/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bookingem</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/scripts.js' %}"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
</body>
</html>

library/webapp/templates/book_detail.html
{% extends 'base.html' %}
{% block title %}{{ book.title }}{% endblock %}
{% block content %}
    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <h1 class="display-4">{{ book.title }}</h1>
            <img src="" alt="{{ book.photo }}">
            <p class="lead">{{ book.description }}</p>
            <a>Автор {{ book.author.name }} {{ book.author.surname }}</a>
            {% if user.is_superuser %}
                <button type="button" class="btn btn-outline-light"><a href="{% url 'webapp:book_update' book.pk %}">редактировать</a>
                </button>
                <button class="btn btn-outline-light"><a href="{% url 'webapp:book_delete' book.pk %}"
                                                         data-toggle="modal"
                                                         data-target="#exampleModal{{ book.pk }}"><span
                        class="font-weight-bold">Удалить</span></a></button>
                <div class="modal fade" id="exampleModal{{ book.pk }}" tabindex="-1" role="dialog"
                     aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Вы уверены?</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                Вы уверены что хотите удалить книгу?
                            </div>
                            <div class="modal-footer">
                                <a href="{% url 'webapp:book_delete' book.pk %}" class="btn btn-secondary">Да</a>
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Нет</button>
                            </div>
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

library/webapp/templates/book_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Bookingem{% endblock %}
{% block content %}
   {% for book in book_list %}
    <div class="jumbotron">
      <h1 class="display-4"><a href="{% url 'webapp:book_detail' book.pk %}">{{ book.title }}</a></h1>
      <hr class="my-4">
      <p>{{ book.description }}</p>
    <a class="btn btn-primary btn-lg" href="{% url 'webapp:author_detail' book.author.id  %}" role="button">{{ book.author.name }} {{ book.author.surname }}</a>
    </div>
    {% endfor %}
{% endblock %}

library/webapp/templates/book_update.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    <div class="container">
        <form action="{% url 'webapp:book_update' book.pk %}" method="post" class="mt-4">
            {% csrf_token %}
                {{ form.as_p }}
            <button class="btn btn-sm btn-outline-info">Submit</button>
        </form>
    </div>
{% endblock %}

library/webapp/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark mb-0 border-bottom pb-0">
    <div class="container">
        <nav class="navbar navbar-light bg-dark">
            <a class="navbar-brand" href="{% url 'webapp:book_list' %}">
                <span class="h3 mb-0 pb-0 font-weight-bold">Bookingem</span>
            </a>
            <a class="navbar-brand" href="{% url 'webapp:author_list' %}">
                <span class="h6 mb-0 pb-0 font-weight-bold">Писатели</span>
            </a>
                {% if user.is_authenticated %}
                    <li class="nav-item navbar-text">Привет, <a
                            href="{% url 'webapp:user_info' user.pk %}">{{ user.username }}</a>
                    </li>
                    <li class="nav-item"><a href="{% url 'accounts:logout' %}" class="nav-link text-light">Выход</a>
                    </li>
                {% else %}
                    <li class="nav-item"><a href="{% url 'accounts:login' %}" class="nav-link text-light">Вход</a></li>
                {% endif %}
            </div>
    </div>
</nav>

library/webapp/templates/user_info.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    <div class="container content">
        <div class="row" style="margin-left: 20px;">
            <div class="col5">
                {% if selected_user.userinfo.avatar %}
                    <img src="{{ selected_user.avatar.url }}" class="avatar-img img-thumbnail" style="width: 15rem;, height: 15rem;">
                {% else %}
                    <img src="{% static 'img/user.jpg' %}" class="avatar-img img-thumbnail">
                {% endif %}
                <br>
                <br>
                {% if selected_user.id == user.id %}
                    <a href="{% url 'webapp:user_edit' user.pk %}" class="btn btn-sm btn-info">Редактировать профиль</a>
                {% endif %}
            </div>
            <div class="col">
                <dl class="row">
                    <dt class="col-sm-3 text-right">Логин</dt>
                    <dd class="col-sm-9">{{ selected_user }}</dd>


                    <dt class="col-sm-3 text-right">Избранное</dt>
                        {% for user_bookmark in selected_user.bookmarks.all %}
                            <dd class="col-sm-9">{{ user_bookmark.user }}</dd>
                    {% endfor %}

                </dl>
            </div>
        </div>

    </div>
{% endblock %}